select RXCUI_DATA.FULL_GENERIC_NAME, PLAN_INFO.FORMULARY_ID,FORMULARY_DATA.RXCUI, 
            FORMULARY_DATA.TIER_LEVEL_VALUE, 
            FORMULARY_DATA.PRIOR_AUTHORIZATION_YN,PLAN_INFO.CONTRACT_ID, 
            PLAN_INFO.PLAN_ID,PLAN_INFO.PREMIUM,PLAN_INFO.DEDUCTIBLE, 
            PLAN_INFO.PDP_REGION_CODE  
     from FORMULARY_DATA join PLAN_INFO  
     on substr(FORMULARY_DATA.FORMULARY_ID,4) = (PLAN_INFO.FORMULARY_ID)  
     join RXCUI_DATA on FORMULARY_DATA.RXCUI = RXCUI_DATA.RXCUI  
     where PLAN_INFO.PDP_REGION_CODE is '4' and  
           PLAN_INFO.CONTRACT_ID like 'S%' and  
           upper(RXCUI_DATA.FULL_GENERIC_NAME) like '%ALLOPURINOL%' and  
           RXCUI_DATA.STRENGTH like '300%'
